<?php

// ----------------------------------------------------------------------------------------------------------
// Interface !
$lang['nfo_page_title']  = "Information";
$lang['nfo_title_head']  = "Information der";
$lang['nfo_name']        = "Name";
$lang['nfo_destroy']     = "Abbaun einer Gebaeude stufe:";
$lang['nfo_level']       = "Stufe";
$lang['nfo_range']       = "Reichweite der Sensoren";
$lang['nfo_used_energy'] = "Energie Verbrauch";
$lang['nfo_used_deuter'] = "Deuterium Verbrauch";
$lang['nfo_prod_energy'] = "Energieerzeugung";
$lang['nfo_difference']  = "Differenz";
$lang['nfo_prod_p_hour'] = "Produktion pro Stunde [Gewinn]";
$lang['nfo_needed']      = "Erfordert";
$lang['nfo_dest_durati'] = "Abbau dauer";

$lang['nfo_struct_pt']   = "Strukturpunkte";
$lang['nfo_shielf_pt']   = "Schildstaerke";
$lang['nfo_attack_pt']   = "Angriffswert";
$lang['nfo_rf_again']    = "Rapidfire gegen";
$lang['nfo_rf_from']     = "Rapidfire von";
$lang['nfo_capacity']    = "Ladekapazitaet";
$lang['nfo_units']       = "Einheiten";
$lang['nfo_base_speed']  = "Geschwindichkeit";
$lang['nfo_consumption'] = "Deuterium verbrauch";

// ----------------------------------------------------------------------------------------------------------
// Interface porte de saut
$lang['gate_start_moon'] = "Ausgangspunkt Mond";
$lang['gate_dest_moon']  = "Reiseziel Mond";
$lang['gate_use_gate']   = "Verwenden des Sprungtores";
$lang['gate_ship_sel']   = "Anzahl der Schiffe";
$lang['gate_ship_dispo'] = "Verfuegbar";
$lang['gate_jump_btn']   = "Aufladen";
$lang['gate_jump_done']  = "Naester Sprung durch Sprungtors jetzt Moeglich: ";
$lang['gate_wait_dest']  = "Die Energie des Ziel Sprungtors hat sich noch nicht geladen: ";
$lang['gate_no_dest_g']  = "Es gibt kein Sprungtor auf diesen Planeten !";
$lang['gate_wait_star']  = "Die Energie des Sprungtors wurde verbraucht, zeit bis aufladung ";
$lang['gate_wait_data']  = "Fehler, es gibt keine Daten, ueber den Prungtor !";

// ----------------------------------------------------------------------------------------------------------
// Batiments Mines!
$lang['info'][1]['name']          = "Metallmine";
$lang['info'][1]['description']   = "Hauptrohstofflieferanten f&uuml;r den Bau tragender Strukturen von Bauwerken und Schiffen. Metall ist der billigste Rohstoff, daf&uuml;r wird er mehr ben&ouml;tigt als die anderen. Metall braucht zur Herstellung am wenigsten Energie. Je gr&ouml;&szlig;er die Minen ausgebaut sind, desto tiefer sind sie. Bei den meisten Planeten befindet sich das Metall in gro&szlig;er Tiefe, durch diese tieferen Minen k&ouml;nnen mehr Metalle abgebaut werden, die Produktion steigt. Gleichzeitig muss f&uuml;r die gr&ouml;&szlig;ere Metallmine mehr Energie zur Verf&uuml;gung gestellt werden.";
$lang['info'][2]['name']          = "Kristallmine";
$lang['info'][2]['description']   = "Baut Mineralien ab die fuer die Feinelektronik benoetigt werden, sie benoetigt jedoch mehr da sie die Mineralien gleich in Noetigen Leggierungen verarbeitet.";
$lang['info'][3]['name']          = "Deuteriumsynthetisierer";
$lang['info'][3]['description']   = "Deuterium ist schwerer Wasserstoff. Daher sind &auml;hnlich wie bei den Minen die gr&ouml;&szlig;ten Vorr&auml;te auf dem Grund des Meeres. Der Ausbau des Synthetisierers sorgt ebenfalls f&uuml;r die Erschlie&szlig;ung dieser Deuterium-Tiefenlagerst&auml;tten. Deuterium wird als Treibstoff f&uuml;r die Schiffe, f&uuml;r fast alle Forschungen, f&uuml;r einen Blick in die Galaxie sowie f&uuml;r den Sensorphalanx-Scan ben&ouml;tigt.";

// ----------------------------------------------------------------------------------------------------------
// Batiments Energie!
$lang['info'][4]['name']          = "Solarkraftwerk";
$lang['info'][4]['description']   = "Um die Energie zur Versorgung der Minen und Synthetisierern zu gew&auml;hrleisten, sind riesige Solarkraftwerkanlagen von N&ouml;ten. Je gr&ouml;&szlig;er die Anlagen ausgebaut sind, desto mehr Oberfl&auml;che ist mit photovoltaischen Zellen bedeckt, welche Lichtenergie in elektrische Energie umwandeln. Solarkraftwerke stellen den Grundstock der planetaren Energieversorgung dar.";
$lang['info'][12]['name']         = "Atomkraftwerk";
$lang['info'][12]['description']  = "In den Atomkraftwerk werden Atome gespalten um so mehr energie erzeugen als in Solarkraftwerk. Ist jedoch sehr teuer im Bau.";

// ----------------------------------------------------------------------------------------------------------
// Batiments GÃ©nÃ©raux!
$lang['info'][14]['name']         = "Roboterfabrik";
$lang['info'][14]['description']  = "Roboterfabriken stellen einfache Arbeitskr&auml;fte zur Verf&uuml;gung, die beim Bau der planetaren Infrastruktur eingesetzt werden k&ouml;nnen. Jede Stufe erh&ouml;ht damit die Geschwindigkeit des Ausbaus von Geb&auml;uden.";
$lang['info'][15]['name']         = "Nanitenfabrik";
$lang['info'][15]['description']  = "Die Nanitenfabrik ist die Kr&ouml;nung der Robotertechnik. Naniten sind nanometergro&szlig;e Roboter, die durch Vernetzung zu au&szlig;erordentlichen Leistungen im Stande sind. Einmal erforscht erh&ouml;hen sie die Produktivit&auml;t in fast allen Bereichen. Die Nanitenfabrik halbiert pro Stufe die Bauzeit von Geb&auml;uden, Schiffen und Verteidigungsanlagen.";
$lang['info'][21]['name']         = "Raumschiffwerft";
$lang['info'][21]['description']  = "In der planetaren Werft werden alle Arten von Schiffen und Verteidigungsanlagen gebaut. Je gr&ouml;&szlig;er sie ist, desto schneller k&ouml;nnen aufw&auml;ndigere und gr&ouml;&szlig;ere Schiffe und Verteidigungsanlagen gebaut werden. Durch Anbau einer Nanitenfabrik werden winzige Roboter erstellt, die den Arbeitern helfen, schneller zu arbeiten.";
$lang['info'][22]['name']         = "Metallspeicher";
$lang['info'][22]['description']  = "Riesige Lagerst&auml;tte f&uuml;r abgebautes Metallerz. Je gr&ouml;&szlig;er der Speicher, desto mehr Metall kann in ihm gelagert werden. Ist das Lager voll, wird kein Metall mehr abgebaut.";
$lang['info'][23]['name']         = "Kristallspeicher";
$lang['info'][23]['description']  = "Das noch unbearbeitete Kristall wird in diesen riesigen Lagerhallen zwischengespeichert. Je gr&ouml;&szlig;er das Lager, desto mehr Kristall kann in ihm eingelagert werden. Sind die Kristalllager voll, wird kein weiteres Kristall abgebaut.";
$lang['info'][24]['name']         = "Deuteriumspeicher";
$lang['info'][24]['description']  = "Riesige Tanks zur Lagerung des neu gewonnenen Deuteriums. Diese Lager findet man meistens in der N&auml;he von Raumh&auml;fen. Je gr&ouml;&szlig;er sie sind, desto mehr Deuterium kann in ihnen gelagert werden. Sind sie gef&uuml;llt, wird kein Deuterium mehr abgebaut.";
$lang['info'][31]['name']         = "Forschungslabor";
$lang['info'][31]['description']  = "Um neue Technologien zu erforschen, ist der Betrieb einer Forschungsstation notwendig. Die Ausbaustufe einer Forschungsstation ist ausschlaggebend daf&uuml;r, wie schnell eine neue Technologie erforscht werden kann. Je h&ouml;her die Ausbaustufe des Labors, umso mehr neue Technologien k&ouml;nnen erforscht werden. Um die Forschungsarbeiten m&ouml;glichst schnell zum Abschluss zu bringen, werden, wenn auf einem Planeten geforscht wird, automatisch alle verf&uuml;gbaren Forscher in diese Forschungsstation geschickt und stehen somit auf anderen Planeten nicht mehr zur Verf&uuml;gung. Sobald eine Technologie einmal erforscht ist, kehren die Forscher auf ihre Heimatplaneten zur&uuml;ck und bringen das Wissen um sie mit. So kann man die Technologie auf all seinen Planeten einsetzen.";
$lang['info'][33]['name']         = "Terraformer";
$lang['info'][33]['description']  = "Mit zunehmendem Ausbau der Planeten, wurde die Frage des begrenzten Lebensraums auf Kolonien immer wichtiger. Traditionelle Methoden wie Hoch- und Tiefbau erwiesen sich zunehmend als unzureichend. Eine kleine Gruppe von Hochenergiephysikern und Nanotechnikern fand schlie&szlig;lich die L&ouml;sung: Das TerraformingUnter Aufwand riesiger Energiemengen kann der Terraformer ganze Landstriche oder gar Kontinente urbar machen. In diesem Geb&auml;ude werden fortw&auml;hrend eigens daf&uuml;r konstruierte Naniten produziert, die f&uuml;r eine konstante Qualit&auml;t des Bodens sorgen.Einmal gebaut kann der Terraformer nicht wieder abgerissen werden.";
$lang['info'][34]['name']         = "Allianzdepot";
$lang['info'][34]['description']  = "Das Allianzdepot bietet die M&ouml;glichkeit, befreundete Flotten, die bei der Verteidigung helfen und im Orbit stehen, mit Treibstoff zu versorgen. F&uuml;r jeden Ausbaulevel des Allianzdepots k&ouml;nnen 10.000 Einheiten Deuterium pro Stunde an die zu versorgenden Flotten im Orbit geschickt werden.";

// ----------------------------------------------------------------------------------------------------------
// Batiments Lune!
$lang['info'][41]['name']         = "Apollo 13 Mondbasis";
$lang['info'][41]['description']  = "Ein Mond verf&uuml;gt &uuml;ber keinerlei Atmosph&auml;re, deshalb muss vor der Besiedlung eine Mondbasis errichtet werden. Diese sorgt f&uuml;r die n&ouml;tige Atemluft, Gravitation und W&auml;rme. Je h&ouml;her die Ausbaustufe der Mondbasis ist, umso gr&ouml;sser ist die Fl&auml;che die mit einer Biosph&auml;re versorgt wird. Pro Mondbasislevel k&ouml;nnen 3 Felder bebaut werden bis zum Maximum der Mondgr&ouml;sse. Diese betr&auml;gt (Durchmesser des Mondes/1000)^2, wobei jede Stufe der Mondbasis selbst auch ein Feld belegt Einmal gebaut kann die Mondbasis nicht wieder abgerissen werden.";
$lang['info'][42]['name']         = "Sensorphalanx";
$lang['info'][42]['description']  = "Hochaufl&ouml;sende Sensoren scannen das vollst&auml;ndige Frequenzspektrum aller auf die Phalanx auftreffenden Strahlungen. Hochleistungscomputer kombinieren winzige Energieschwankungen und gewinnen so Informationen &uuml;ber Schiffsbewegungen auf entfernten Planeten. F&uuml;r den Scan muss Energie in Form von Deuterium (5.000) auf dem Mond bereitgestellt werden. Man scannt, indem man vom Mond aus ins Galaxiemenü wechselt und auf einen feindlichen Planeten in Sensorenreichweite (Phalanxstufe)^2 - 1 klickt.";
$lang['info'][43]['name']         = "Sprungtor";
$lang['info'][43]['description']  = "Sprungtore sind riesige Transmitter, die in der Lage sind, selbst gro&szlig;e Flotten ohne Zeitverlust durch das Universum zu versenden. Diese Transmitter verbrauchen kein Deuterium, jedoch muss zwischen 2 Spr&uuml;ngen eine Stunde vergehen, da sich die Tore sonst &uuml;berhitzen w&uuml;rden. Auch ist ein Mitschicken von Ressourcen nicht m&ouml;glich. Der ganze Vorgang erfordert eine ungeheuer hoch entwickelte Technologie.";

$lang['info'][44]['name']         = "Raketensilo";
$lang['info'][44]['description']  = "Raketensilos dienen zum Einlagern von Raketen. Pro ausgebauter Stufe kann man f&uuml;nf Interplanetar- oder zehn Abfangraketen einlagern. Eine Interplanetarrakete ben&ouml;tigt soviel Platz wie zwei Abfrangraketen. Unterschiedliche Raketentypen k&ouml;nnen beliebig kombiniert werden.";

// ----------------------------------------------------------------------------------------------------------
// Laboratoire !
$lang['info'][106]['name']        = "Spionagetechnik";
$lang['info'][106]['description'] = "Die Spionagetechnik befasst sich in erster Linie mit der Erforschung neuer und effizienterer Sensoren. Je h&ouml;her diese Technik entwickelt ist, umso mehr Informationen stehen dem Nutzer &uuml;ber Vorg&auml;nge in seiner Umgebung zur Verf&uuml;gung. F&uuml;r Sonden ist die Differenz des eigenen und des gegnerischen Spionagelevels entscheidend. Je weiter die eigene Spionagetechnik erforscht ist, desto mehr Informationen enth&auml;lt der Bericht und um so kleiner ist die Chance , dass man beim Spionieren entdeckt wird. Je mehr Sonden man schickt, desto mehr Details erf&auml;hrt man von seinem Gegner, gleichzeitig steigt aber auch die Gefahr einer Entdeckung. Die Spionagetechnik verbessert ebenfalls die Ortung fremder Flotten. Dabei ist nur der eigene Spionagelevel entscheidend. Ab Level 2 wird zus&auml;tzlich zur reinen Angriffsmeldung auch die Gesamtanzahl der angreifenden Schiffe angezeigt. Ab Level 4 sieht man die Art der angreifenden Schiffe, sowie die Gesamtanzahl und ab Level 8 die genaue Anzahl der verschiedenen Schiffs-Typen. F&uuml;r Raider ist diese Technik unverzichtbar, da sie Auskunft dar&uuml;ber gibt, ob das Opfer Flotte und/oder Verteidigung stationiert hat oder nicht. Deshalb sollte diese Technik schon sehr fr&uuml;h erforscht werden. Am besten sofort nach der Erforschung von Kleinen Transportern.";
$lang['info'][108]['name']        = "Computertechnik";
$lang['info'][108]['description'] = "Die Computertechnik befasst sich mit der Erweiterung der vorhandenen Computerkapazit&auml;ten. Immer leistungsf&auml;higere und effizientere Computersysteme werden entwickelt. Die Rechenleistung steigt immer weiter und die Geschwindigkeit, mit denen Rechenprozesse ablaufen, wird ebenfalls erh&ouml;ht. Mit der Erh&ouml;hung der Computerkapazit&auml;ten lassen sich immer mehr Flotten gleichzeitig befehligen. Jede Stufe Computertechnik erh&ouml;ht dabei die maximale Flottenanzahl um eins. Je mehr Flotten man gleichzeitig verschicken kann, desto mehr kann man raiden und desto mehr Rohstoffe kann man einnehmen. Nat&uuml;rlich nutzt diese Technik auch H&auml;ndlern, denn sie k&ouml;nnen dann ebenfalls mehr Handelsflotten gleichzeitig losschicken. Aus diesem Grund sollte die Computertechnik kontinuierlich &uuml;ber das gesamte Spiel hinweg ausgebaut werden.";
$lang['info'][109]['name']        = "Waffentechnik";
$lang['info'][109]['description'] = "Die Waffentechnik besch&auml;ftigt sich vor allem mit der Weiterentwicklung bestehender Waffensysteme. Dabei wird insbesondere darauf Wert gelegt, die vorhandenen Systeme mit mehr Energie auszustatten und diese Energie punktgenauer zu kanalisieren. Dadurch werden die Waffensysteme effizienter und Waffen richten mehr Schaden an. Jede Stufe der Waffentechnik erh&ouml;ht die Waffenst&auml;rke der Einheiten um 10% des Grundwertes. Die Waffentechnik ist wichtig, um sp&auml;ter die eigenen Einheiten konkurrenzf&auml;hig zu halten. Deshalb sollte sie kontinuierlich das ganze Spiel hindurch entwickelt werden.";
$lang['info'][110]['name']        = "Schildtechnik";
$lang['info'][110]['description'] = "Die Schildtechnik besch&auml;ftigt sich mit der Erforschung immer neuer M&ouml;glichkeiten, die Schilde mit mehr Energie zu versorgen und sie so effizienter und belastbarer zu machen. Dadurch steigt mit jeder erforschten Stufe die Effizienz der Schilde um 10% des Grundwertes.";
$lang['info'][111]['name']        = "Raumschiffpanzerrung";
$lang['info'][111]['description'] = "Spezielle Legierungen machen die Panzerung der Raumschiffe immer besser. Ist einmal eine sehr widerstandsf&auml;hige Legierung gefunden, wird durch spezielle Strahlungen die molekulare Struktur des Raumschiffes ver&auml;ndert und auf den Stand der besten erforschten Legierung gebracht. Die Wirksamkeit der Panzerung kann so pro Stufe um 10% des Grundwertes gesteigert werden.";
$lang['info'][113]['name']        = "Energietechnologie";
$lang['info'][113]['description'] = "Die Energietechnik besch&auml;ftigt sich mit der Weiterentwicklung der Energieleitsysteme und Energiespeicher, welche f&uuml;r viele neue Technologien ben&ouml;tigt wird.";
$lang['info'][114]['name']        = "Hyperraumtechnik";
$lang['info'][114]['description'] = "Durch die Einbindung der 4. und 5. Dimension ist es nun m&ouml;glich einen neuartigen Antrieb zu erforschen, welcher sparsamer und leistungsf&auml;higer ist.";
$lang['info'][115]['name']        = "Verbrennungstriebwerk";
$lang['info'][115]['description'] = "Verbrennungstriebwerke basieren auf dem uralten Prinzip des R&uuml;ckstosses. Hocherhitzte Materie wird weggeschleudert und treibt das Schiff in die entgegengesetzte Richtung. Der Wirkungsgrad dieser Triebwerke ist eher gering, aber sie sind billig und zuverl&auml;ssig und ben&ouml;tigen kaum Wartung. Au&szlig;erdem verbrauchen sie weniger Raum und sind deshalb gerade auf kleineren Schiffen immer wieder zu finden. Da Verbrennungstriebwerke die Grundlage jeder Raumfahrt sind, sollten sie so fr&uuml;h wie m&ouml;glich erforscht werden. Die Weiterentwicklung dieser Triebwerke macht folgende Schiffe um 10% des Grundwertes pro Stufe schneller: Kleine und gro&szlig;e Transporter, Leichte J&auml;ger, Recycler und Spionagesonden.";
$lang['info'][117]['name']        = "Impulstriebwerk";
$lang['info'][117]['description'] = "Das Impulstriebwerk basiert auf dem R&uuml;cksto&szlig;prinzip, wobei die Strahlmasse zum Gro&szlig;teil als Abfallprodukt der zur Energiegewinnung verwendeten Kernfusion entsteht. Zus&auml;tzlich kann weitere Masse eingespritzt werden. Die Weiterentwicklung dieser Triebwerke macht folgende Schiffe um 20% des Grundwertes pro Stufe schneller: Bomber, Kreuzer, Schwere J&auml;ger und Kolonieschiffe. Interplanetarraketen k&ouml;nnen pro Stufe weiter fliegen.";
$lang['info'][118]['name']        = "Hyperraumantrieb";
$lang['info'][118]['description'] = "Durch eine Raumzeitverkr&uuml;mmung wird in unmittelbarer Umgebung eines Schiffes der Raum komprimiert, womit sich weite Strecken sehr schnell zur&uuml;cklegen lassen. Je h&ouml;her der Hyperraumantrieb entwickelt ist, desto h&ouml;her wird die Kompression des Raumes, wodurch sich pro Stufe die Geschwindigkeit der Schiffe die damit ausgestattet sind (Schlachtkreuzer, Schlachtschiffe, Zerst&ouml;rer und Todessterne) um 30% erh&ouml;ht. Voraussetzungen: Hyperraumtechnik (Stufe 3) Forschungslabor (Stufe 7).";
$lang['info'][120]['name']        = "Lasertechnik";
$lang['info'][120]['description'] = "Laser (Lichtverst&auml;rkung durch induzierte Strahlungsemission) erzeugen einen intensiven, energiereichen Strahl von koh&auml;rentem Licht. Diese Ger&auml;te finden in allen m&ouml;glichen Bereichen ihre Anwendung, von optischen Computern bis hin zu schweren Laserwaffen, die m&uuml;helos durch Raumschiffpanzerungen schneiden. Die Lasertechnik bildet einen wichtigen Grundstein f&uuml;r die Erforschung weiterer Waffentechnologien. Voraussetzungen: Forschungslabor (Stufe 1) Energietechnik (Stufe 2).";
$lang['info'][121]['name']        = "Ionentechnik";
$lang['info'][121]['description'] = "Wahrhaft t&ouml;dlicher Richtstrahl aus beschleunigten Ionen. Die beschleunigten Ionen richten beim Auftreffen auf ein Objekt einen riesigen Schaden an.";
$lang['info'][122]['name']        = "Plasmatechnik";
$lang['info'][122]['description'] = "Eine Weiterentwicklung der Ionentechnik, die nicht Ionen beschleunigt, sondern hochenergetisches Plasma. Das hochenergetische Plasma hat eine verheerende Wirkung beim Auftreffen auf ein Objekt.";
$lang['info'][123]['name']        = "Intergalaktisches Forschungsnetzwerk";
$lang['info'][123]['description'] = "Forscher verschiedener Planeten kommunizieren &uuml;ber dieses Netzwerk miteinander.Pro erforschtes Level, wird ein Forschungslabor vernetzt. Dabei werden immer die Labors der h&ouml;chsten Stufe dazugeschaltet.Das vernetzte Labor muss ausreichend ausgebaut sein um die anstehende Forschung selbst&auml;ndig durchf&uuml;hren zu k&ouml;nnen. Die Ausbaustufen aller beteiligten Labors werden im intergalaktischen Forschungsnetzwerk zusammen gez&auml;hlt.";
$lang['info'][124]['name']        = "Expeditionstechnik";
$lang['info'][124]['description'] = "Expeditionstechnik umfasst verschiedene Scanntechnologien und ermöglicht Raumschiffe diverser Größen mit einem Forschungsmodul auszurüsten. Dieses beinhaltet eine Datenbank und ein voll ausgestattetes mobiles Labor. Um bei gefährlichen Forschungsobjekten die Sicherheit des Schiffes zu gewähren, verfügt das Forschungsmodul über eine eigene Energieversorgung und einen Energiefeldgenerator, der im Notfall das Forschungsmodul mit einem starken Kraftfeld umgeben kann.";
$lang['info'][199]['name']        = "Gravitonforschung";
$lang['info'][199]['description'] = "Ein Graviton ist ein Partikel, das keine Masse und keine Ladung besitzt, welche die Gravitationskraft bestimmt. Durch Abschuss einer konzentrierten Ladung von Gravitonen kann ein k&uuml;nstliches Gravitationsfeld errichtet werden, welches &auml;hnlich einem schwarzen Loch, Masse in sich hineinzieht, wodurch Schiffe oder auch Monde vernichtet werden k&ouml;nnen. Um eine ausreichende Menge Gravitonen herzustellen ben&ouml;tigt es riesige Mengen an Energie. Voraussetzungen: Forschungslabor (Stufe 15).";

// ----------------------------------------------------------------------------------------------------------
// Flotte !
$lang['info'][202]['name']        = "Kleiner Transporter";
$lang['info'][202]['description'] = "Transporter haben ungef&auml;hr die gleiche Gr&ouml;&szlig;e wie J&auml;ger, verzichten aber auf leistungsf&auml;hige Antriebe und Bordwaffen, um Platz f&uuml;r Frachtraum zu schaffen. Der kleine Transporter verf&uuml;gt &uuml;ber eine Ladekapazit&auml;t von 10.000 Ressourceneinheiten. Aufgrund ihrer geringen Feuerkraft werden Transporter oft von anderen Schiffen eskortiert.";
$lang['info'][203]['name']        = "Gro&szlig;er Transporter";
$lang['info'][203]['description'] = "Dieses Schiff hat kaum Waffen oder andere Technologien an Bord. Aus diesem Grunde sollten sie nie alleine losgeschickt werden. Der gro&szlig;e Transporter dient durch sein hochentwickeltes Verbrennungstriebwerk als schneller Ressourcenlieferant zwischen den Planeten und nat&uuml;rlich begleitet er die Flotten auf ihren &uuml;berf&auml;llen feindlicher Planeten, um m&ouml;glichst viele Ressourcen zu erobern, der Gro&szlig;e Transporter verf&uuml;gt &uuml;ber eine Ladekapazit&auml;t von 50.000 Ressourceneinheiten.";
$lang['info'][204]['name']        = "Leichter Jaeger";
$lang['info'][204]['description'] = "Der leichte J&auml;ger ist ein wendiges Schiff, das auf fast jedem Planeten vorgefunden wird. Die Kosten sind nicht besonders hoch, Schildst&auml;rke und Ladekapazit&auml;t sind allerdings sehr gering.";
$lang['info'][205]['name']        = "Schwerer Jaeger";
$lang['info'][205]['description'] = "Bei der Weiterentwicklung des leichten J&auml;gers kamen die Forscher zu einem Punkt, bei welchem der konventionelle Antrieb nicht mehr ausreichend Leistungen erbrachte. Um das neue Schiff optimal fortbewegen zu k&ouml;nnen wurde zum ersten Mal der Impulsantrieb genutzt. Dieses erh&ouml;hte zwar die Kosten, er&ouml;ffnete aber auch neue M&ouml;glichkeiten. Durch die Einsetzung dieses Antriebes blieb mehr Energie f&uuml;r Waffen und Schilde &uuml;brig, au&szlig;erdem wurden f&uuml;r diese neue J&auml;gergattung auch qualitativ hochwertigere Materialien verwendet. Dies f&uuml;hrte zu einer verbesserten strukturellen Integrit&auml;t und einer h&ouml;heren Feuerkraft, was ihn im Kampf zu einer immens gr&ouml;&szlig;eren Bedrohung macht als sein leichtes Pendant. Durch diese &auml;nderungen stellt der schwere J&auml;ger eine neue &auml;ra der Schiffstechnologie dar, welche die Grundlage f&uuml;r die Kreuzertechnologie ist.";
$lang['info'][206]['name']        = "Kreuzer";
$lang['info'][206]['description'] = "Mit der Entwicklung der schweren Laser und der Ionenkanonen kamen die J&auml;ger immer mehr in Bedr&auml;ngnis. Trotz vieler Modifikationen konnte die Waffenst&auml;rke und die Panzerung nicht so weit gesteigert werden, um diesen Verteidigungsgesch&uuml;tzen wirksam begegnen zu k&ouml;nnen. Deshalb entschied man sich, eine neue Schiffsklasse zu konstruieren, die mehr Panzerung und mehr Feuerkraft in sich vereinte. Der Kreuzer war geboren. Kreuzer sind fast dreimal so stark gepanzert wie schwere J&auml;ger und verf&uuml;gen &uuml;ber mehr als die doppelte Schusskraft. Zudem sind sie sehr schnell. Gegen mittlere Verteidigung gibt es keine bessere Waffe. Kreuzer beherrschten fast ein Jahrhundert lang unumschr&auml;nkt das All. Mit dem Aufkommen der Gau&szlig;gesch&uuml;tze und Plasmawerfer endete ihre Vorherrschaft. Jedoch werden sie auch heute noch gerne gegen J&auml;gerverb&auml;nde eingesetzt.";
$lang['info'][207]['name']        = "Schlachtschiff";
$lang['info'][207]['description'] = "Schlachtschiffe bilden meist das R&uuml;ckgrat einer Flotte. Ihre schweren Gesch&uuml;tze, die hohe Geschwindigkeit und der gro&szlig;e Frachtraum machen sie zu ernst zu nehmenden Gegnern.";
$lang['info'][208]['name']        = "Kolonieschiff";
$lang['info'][208]['description'] = "Dieses gut gepanzerte Schiff dient der Eroberung neuer Planeten, was f&uuml;r ein aufstrebendes Imperium unerl&auml;sslich ist. Das Schiff wird auf der neuen Kolonie als Rohstofflieferant genutzt, in dem es wieder auseinander gebaut wird und alles wiederverwertbare Material f&uuml;r die Erschlie&szlig;ung der Neuen Welt genutzt wird. Pro Imperium k&ouml;nnen inklusive Hauptplanet maximal 9 Planeten kolonisiert werden.";
$lang['info'][209]['name']        = "TF Sammler";
$lang['info'][209]['description'] = "Die Weltraumgefechte nahmen immer gr&ouml;&szlig;ere Ausma&szlig;e an. Tausende Schiffe wurden zerst&ouml;rt, aber die dadurch entstehenden Tr&uuml;mmerfelder schienen f&uuml;r immer verloren. Normale Transporter konnten sich nicht nahe genug an diese Felder heran bewegen, ohne durch kleinere Tr&uuml;mmer riesigen Schaden zu nehmen. Mit einer neuen Entwicklung im Bereich der Schildtechnologie konnte dieses Problem effizient beseitigt werden, es entstand eine neue Schiffsklasse, &auml;hnlich dem gro&szlig;en Transporter, der TF Sammler . Mit dessen Hilfe konnten die scheinbar verlorenen Ressourcen doch noch verwertet werden. Die kleinen Tr&uuml;mmer stellten aufgrund der neuen Schilde auch keine Gefahr mehr dar. Leider ben&ouml;tigen diese Vorrichtungen Platz, dadurch ist seine Ladekapazit&auml;t auf 40.000 beschr&auml;nkt.";
$lang['info'][210]['name']        = "Spionagesatellit";
$lang['info'][210]['description'] = "Spionagesonden sind kleine wendige Drohnen, welche &uuml;ber weite Entfernungen hinweg Daten &uuml;ber Flotten und Planeten liefern. Ihr Hochleistungstriebwerk erm&ouml;glicht ihnen weite Strecken in wenigen Sekunden zur&uuml;ck zu legen. Einmal in der Umlaufbahn eines Planeten angekommen verweilen sie dort kurz um Daten zu sammeln. W&auml;hrend dieser Zeit sind sie vom Feind relativ leicht entdeck- und angreifbar. Um Platz zu sparen wurde auf Panzerung, Schilde und Waffen verzichtet, was die Sonden, wenn sie einmal entdeckt wurden, zu leichten Zielen macht.";
$lang['info'][211]['name']        = "Bomber";
$lang['info'][211]['description'] = "Der Bomber wurde speziell entwickelt um die Verteidigung eines Planeten zu zerst&ouml;ren. Mit Hilfe einer lasergesteuerten Zielvorrichtung wirft er zielgenau Plasmabomben auf die Planetenoberfl&auml;che und richtet so einen verheerenden Schaden bei Verteidigungsanlagen an.";
$lang['info'][212]['name']        = "Solarsatellit";
$lang['info'][212]['description'] = "Solarsatelliten werden in eine geostation&auml;re Umlaufbahn um einen Planeten geschossen. Sie b&uuml;ndeln Sonnenenergie und transferieren sie zu einer Bodenstation. Die Effizienz der Solarsatelliten h&auml;ngt von der St&auml;rke der Sonneneinstrahlung ab. Grunds&auml;tzlich ist die Energieausbeute auf sonnennahen Orbits gr&ouml;&szlig;er als auf Planeten mit sonnenfernen Orbit. Durch ihr gutes Preis/Leistungsverh&auml;ltnis l&ouml;sen Solarsatelliten die Energieprobleme vieler Welten. Aber Vorsicht: Solarsatelliten k&ouml;nnen im Kampf zerst&ouml;rt werden.";
$lang['info'][213]['name']        = "Zerst&ouml;rer";
$lang['info'][213]['description'] = "Der Zerst&ouml;rer ist der K&ouml;nig unter den Kriegsschiffen. Seine Multiphalanx Ionen-, Plasma- und Gau&szlig;gesch&uuml;tzt&uuml;rme k&ouml;nnen durch ihre verbesserten Anpeilungssensoren fast 99% der verteidigenden leichten Laser treffen. Da der Zerst&ouml;rer sehr gro&szlig; ist, ist seine Man&ouml;vrierf&auml;higkeit stark eingeschr&auml;nkt, wodurch er im Kampf eher einer Kampfstation gleicht, als einem Kampfschiff. So hoch wie seine Kampfkraft ist auch sein Verbrauch an Deuterium.";
$lang['info'][214]['name']        = "Todesstern";
$lang['info'][214]['description'] = "Der Todesstern ist mit einer riesigen Gravitonkanone bewaffnet, die Schiffe so gro&szlig; wie Zerst&ouml;rer oder sogar Monde zerst&ouml;ren kann. Da daf&uuml;r eine hohe Menge an Energie ben&ouml;tigt wird, besteht er fast nur aus Generatoren. Lediglich riesige Sternenreiche k&ouml;nnen &uuml;berhaupt die Ressourcen und Arbeiter aufbringen, um dieses mondgro&szlig;e Schiff zu bauen.";
$lang['info'][215]['name']        = "Schlachtzreuzer";
$lang['info'][215]['description'] = "Dieses filigrane Schiff eignet sich hervorragend zum Zerst&ouml;ren feindlicher Flottenverb&auml;nde. Mit seinen hochentwickelten Lasergesch&uuml;tzen ist es in der Lage, eine grosse Zahl angreifender Schiffe gleichzeitig zu bek&auml;mpfen. Durch seine schlanke Bauform und die starken Bewaffnung ist die Ladekapazit&auml;t begrenzt. Dies wird jedoch durch den verbrauchsarmen Hyperraumantrieb wieder ausgeglichen.";

// ----------------------------------------------------------------------------------------------------------
// Defenses !
$lang['info'][401]['name']        = "Raketenwerfer";
$lang['info'][401]['description'] = "Der Raketenwerfer ist eine einfache aber kosteng&uuml;nstige Verteidigungsm&ouml;glichkeit. Da er nur eine Weiterentwicklung gew&ouml;hnlicher ballistischer Feuerwaffen ist, ben&ouml;tigt er keine weitere Forschung. Seine geringen Herstellungskosten rechtfertigen seinen Einsatz gegen kleinere Flotten, er verliert aber mit der Zeit an Bedeutung. Sp&auml;ter wird er nur noch als Schussfang hinter gro&szlig;en Gesch&uuml;tzen eingesetzt. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.";
$lang['info'][402]['name']        = "Leichtes Lasergesch&uuml;tz";
$lang['info'][402]['description'] = "Um die enormen Fortschritte im Bereich der Raumschifftechnologie kompensieren zu k&ouml;nnen, mussten die Forscher eine Verteidigungsanlage entwickeln, welche auch mit gr&ouml;&szlig;eren und besser ausger&uuml;steten Schiffen bzw. Flotten zurechtkommt. Dies war die Geburtsstunde des leichten Lasers. Durch den konzentrierten Beschuss eines Ziels mit Photonen konnte eine wesentlich gr&ouml;&szlig;ere Schadenswirkung erzielt werden als mit gew&ouml;hnlichen ballistischen Waffen. Um der gr&ouml;&szlig;eren Feuerkraft der neuen Schiffstypen widerstehen zu k&ouml;nnen wurde er au&szlig;erdem mit verbesserten Schilden ausgestattet. Damit die Produktionskosten dennoch gering gehalten werden konnten wurde die Struktur nicht weiter verst&auml;rkt. Der leichte Laser besitzt das beste Preis-/Leistungsverh&auml;ltnis &uuml;berhaupt und ist dadurch auch f&uuml;r weiter fortgeschrittene Zivilisationen interessant. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich die zerst&ouml;rten Verteidigungsanlagen wieder Instand setzen lassen.";
$lang['info'][403]['name']        = "Schweres Lasergesch&uuml;tz";
$lang['info'][403]['description'] = "Der schwere Laser stellt die konsequente Weiterentwicklung des Designs des leichten Lasers dar. Die Struktur wurde verst&auml;rkt und mit neuen Materialien verbessert. Die H&uuml;lle konnte so wesentlich widerstandsf&auml;higer gemacht werden. Gleichzeitig wurden auch das Energiesystem und der Zielcomputer verbessert, so dass ein schwerer Laser wesentlich mehr Energie auf ein Ziel konzentrieren kann. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.";
$lang['info'][404]['name']        = "Gau&szlig;kanone";
$lang['info'][404]['description'] = "Projektilwaffen galten lange Zeit neben der moderneren Kernfusions- und Energietechnik, der Entwicklung des Hyperraumantriebs und immer besserer Panzerungen als antiquiert, bis eben genau die Energietechnik, die sie einst verdr&auml;ngt hatte, ihr wieder zu ihrem angestammten Platz verhalf. Das Prinzip war eigentlich schon aus dem 20. und 21. Jahrhundert der Erde bekannt - der Teilchenbeschleuniger. Eine Gau&szlig;kanone ist eigentlich nichts anderes als eine erheblich gr&ouml;&szlig;ere Version dieser Konstruktion. Tonnenschwere Geschosse werden unter gigantischem elektrischem Aufwand magnetisch beschleunigt und haben M&uuml;ndungsgeschwindigkeiten, die die Schmutzteilchen in der Luft um das Geschoss verbrennen lassen und der R&uuml;cksto&szlig; bringt die Erde zum beben. Dieser Durchschlagskraft k&ouml;nnen auch aktuelle Panzerungen und Schilde nur schwer widerstehen, und es kommt nicht selten vor, dass das Ziel einfach durchschlagen wird. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.";
$lang['info'][405]['name']        = "Ionengesch&uuml;tz";
$lang['info'][405]['description'] = "Im 21. Jahrhundert der Erde gab es etwas, das allgemein als EMP bekannt war. EMP steht f&uuml;r Elektromagnetischer Puls, der die Eigenschaft hat, in alle Schaltkreise zus&auml;tzliche Spannungen zu induzieren und somit massenhafte St&ouml;rungen zu verursachen, die alle empfindlichen Ger&auml;te zerst&ouml;ren k&ouml;nnen. Damals waren EMP - Waffen meistens noch auf Raketen- und Bombenbasis, auch in Verbindung mit Nuklearwaffen. Mittlerweile wurde der EMP st&auml;ndig weiterentwickelt, da man in ihm ein gro&szlig;es Potential sah, Ziele nicht zu zerst&ouml;ren, aber kampf- und man&ouml;vrierunf&auml;hig zu machen, so dass einer &uuml;bernahme nichts mehr im Wege stand. Die bisher h&ouml;chste Form einer EMP - Waffe stellt das Ionengesch&uuml;tz dar. Es schleudert eine Welle von Ionen (elektrisch geladene Teilchen) auf das Ziel, welche die Schilde destabilisiert und alle Elektronik - sofern diese nicht massiv abgeschirmt ist - besch&auml;digt, was nicht selten einer v&ouml;lligen Zerst&ouml;rung gleichkommt. Die kinetische Durchschlagskraft kann vernachl&auml;ssigt werden. Die Ionentechnik wird auch auf Kreuzern eingesetzt, jedoch auf keinem anderen Schiffstyp, da der Energieverbrauch der Ionengesch&uuml;tze enorm ist und es in einem Gefecht h&auml;ufig darauf ankommt, das Ziel zu zerst&ouml;ren und nicht nur zu paralysieren. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.";
$lang['info'][406]['name']        = "Plasmawerfer";
$lang['info'][406]['description'] = "Die Lasertechnik war mittlerweile nahezu perfektioniert, die Ionentechnik hatte ein Endstadium erreicht und es galt mittlerweile als praktisch unm&ouml;glich, auch aus nur einem Waffensystem qualitativ gesehen noch mehr Effektivit&auml;t herauszubekommen. Doch all dies sollte sich &auml;ndern, als man auf die Idee kam, beide Systeme miteinander zu kombinieren. Schon aus der Kernfusionstechnik bekannt, erhitzen Laser Teilchen ( meistens Deuterium ) auf extrem hohe Temperaturen, die schon einmal in die Millionen Grad gehen. Die Ionentechnik tr&auml;gt ihren Teil in Form von elektrischer Aufladung, Stabilisierungsfeldern und Beschleunigern bei. Wird die abzufeuernde Ladung gen&uuml;gend erhitzt, unter Druck gesetzt und ionisiert, jagt man sie mittels Beschleunigern in die Weiten des Alls Richtung Ziel hinaus. Der gr&uuml;nlich gl&uuml;hende Plasmastrahl bietet einen imposanten Anblick, es fragt sich aber, ob die Crew des Zielschiffes lange an ihm Gefallen haben wird, wenn in wenigen Sekunden die H&uuml;lle zerfetzt und die Elektronik geschmort wird... Der Plasmawerfer gilt als eine der gef&uuml;rchtetsten Waffen &uuml;berhaupt, und diese Technik hat auch ihren Preis. Verteidigungsanlagen deaktivieren sich, sobald sie zu stark besch&auml;digt sind. Nach einer Schlacht betr&auml;gt die Chance bis zu 70%, dass sich ausgefallene Verteidigungsanlagen wieder Instand setzen lassen.";
$lang['info'][407]['name']        = "Kleine Schildkuppel";
$lang['info'][407]['description'] = "Lange bevor die Schildgeneratoren klein genug waren, um auf Schiffen Einsatz zu finden, existierten bereits riesige Generatoren auf der Oberfl&auml;che von Planeten. Diese umh&uuml;llen den ganzen Planeten mit einem Kraftfeld, welches ungeheuere Mengen an Energie absorbieren kann, bevor es zusammenbricht. Kleinere Angriffsflotten scheitern immer wieder an diesen Schildkuppeln. Mit zunehmender technologischer Entwicklung k&ouml;nnen diese Schilde noch verst&auml;rkt werden. Sp&auml;ter kann man sogar eine gro&szlig;e Schildkuppel bauen, die noch st&auml;rker ist. Pro Planet kann nur eine einzige kleine Schildkuppel gebaut werden.";
$lang['info'][408]['name']        = "Grosse Schildkuppel";
$lang['info'][408]['description'] = "Die Weiterentwicklung der kleinen Schildkuppel. Sie basiert auf den gleichen Technologien kann aber wesentlich mehr Energie einsetzen um feindliche Angriffe abzuhalten.";

// ----------------------------------------------------------------------------------------------------------
// Missiles !
$lang['info'][502]['name']        = "Bodenluft Rakete";
$lang['info'][502]['description'] = "Abfangraketen zerst&ouml;ren angreifende Intercontineltalraketen. Jede Bodenluft rakete zerst&ouml;rt eine Interplanetarrakete.";
$lang['info'][503]['name']        = "Intercontineltal Rakete";
$lang['info'][503]['description'] = "Intercontinentalraketen zerst&ouml;ren die gegnerische Verteidigung, k&ouml;nnen allerdings durch Abfangraketen zerst&ouml;rt werden! Von Interplanetarraketen zerst&ouml;rte Verteidigungsanlagen bauen sich nicht wieder auf.";

?>
